name: 'Build'

on:
  push:
    paths:
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - '**.ts'
    branches:
      - 'main'
      - 'develop'
  pull_request:
    paths:
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - '**.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'oven-sh/setup-bun@v1'
      - run: 'bun install'
      - run: 'bun run build'
