name: 'Code Quality'

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'oven-sh/setup-bun@v1'
      - run: 'bun install'
      - run: 'bun run format:check'

  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'oven-sh/setup-bun@v1'
      - run: 'bun install'
      - run: 'bun run lint:check'
