name: 'Test'

on:
  push:
    paths:
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - 'jest.config.ts'
      - '**.ts'
    branches:
      - 'main'
      - 'develop'
  pull_request:
    paths:
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - 'jest.config.ts'
      - '**.ts'
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'oven-sh/setup-bun@v1'
      - run: 'bun install'
      - run: 'bun run test:coverage'
      - name: 'Upload coverage reports to Codecov'
        uses: 'codecov/codecov-action@v3'
        env:
          CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
